### ISSUE TITLE
veth interface

### ISSUE THREAD

**Issue by hyavari** [cneira/firecracker-task-driver#11]
Hi Neira,

When Nomad runs a job for creation of micro VM, it creates a veth interface, but when we stop the job, it doesn't remove that veth.
So, after running some jobs, you would have many veth interfaces on the host machine. It's a bug or we have to do something in the job?

225: vethdc6cd6b7@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:e2:74:60:24:28 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 192.168.127.1/32 scope global vethdc6cd6b7
       valid_lft forever preferred_lft forever
    inet6 fe80::e2:74ff:fe60:2428/64 scope link 
       valid_lft forever preferred_lft forever
230: vethc53f5bdf@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 72:3a:7f:35:a1:e1 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet 192.168.127.1/32 scope global vethc53f5bdf
       valid_lft forever preferred_lft forever
    inet6 fe80::703a:7fff:fe35:a1e1/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by cneira** [comment]
@hyavari 
Thanks for the report,I think is a bug, I'll tag it as such.

**Comment by cneira** [comment]
> @hyavari
> Thanks for the report,I think is a bug, I'll tag it as such.
> I have checked today and is a bug, I'll work on this.

@hyavari 

This has been fixed in version 1.2 of the driver, you could build that branch and follow the
new instructions on how to setup the firecracker-task-driver, the main difference is now the driver needs it's own cni plugins which you need to compile and copy to /opt/cni/bin as the documentation says.
feel free to reopen if this keeps happening.
